= bibi publish

= {doctitle}

* link:https://rubygems.org/gems/bibi-publish[Homepage]
* link:http://rubydoc.info/gems/bibi-publish[Documentation]
* mailto:KitaitiMakoto-at-gmail.com[Email]

== 説明

bibi publishはEPUBファイルをS3にアップロードし、link:https://github.com/satorumurmur/bibi[Bibi]というEPUBリーダーアプリケーションで閲覧可能にするコマンドラインツールです。

== 機能

* EPUBドキュメント内のファイルをAmazon S3上のBibiのbookshelfディレクトリーにアップロード
* EPUB閲覧用のHTMLファイルを作成してS3にアップロード

== 使用例

    % bibi publish moby-dick.epub
    % bibi publish moby-dick.epub moby-dick-book
    % bibi publish --bibi=s3://yourbucket/subdir/bibi moby-dick.epub moby-dick-book

== 前提条件

* AWSアカウント
* S3バケットにファイルをアップロード可能な環境
* アクセス可能で静的ウェブサイトホスティングように設定されたS3バケット
* AWS CLIとその設定

== インストール

    % gem install bibi-publish

== 概要

=== 予行

bibi publishは `--dry-run` オプションをサポートしています。これはアップロード予定のファイルを表示はするが実際にはアップロードしないというオプションです。

    % bibi publish --bibi=s3://yourbucket/subdir/bibi path/to/moby-dick.epub moby-dick-book --dry-run

=== 与えられたバケットとパスへのアップロード

    % bibi publish --bibi=s3://yourbucket/subdir/bibi path/to/moby-dick.epub

これは次のことを行います。

* `moby-dick.epub` というEPUBファイル内のファイルを `s3://yourbucket/subdir/bibi-bookshelf/moby-dick` へアップロード
* Bibiを使ってこのEPUBドキュメントを読むためのHTMLファイルを `s3://yourbucket/subdir/bibi/moby-dick.html` へアップロード

Note that:

* `bibi-bookshelf` というbookshelfディレクトリーはbibi publishが自動的に決定する
* `moby-dick` というbookshelfのサブディレクトリーは、 `moby-dick.epub` という与えられたEPUBファイルからbibi publishが自動的に決定する

=== Bibi bookshelf下のディレクトリー名の指定

    % bibi publish --bibi=s3://yourbucket/subdir/bibi path/to/moby-dick.epub moby-dick-book

`page-blanch-book` という第二引数はS3上のサブディレクトリーとHTMLファイル名に使われます。つまり以下のようになります。

* `s3://yourbucket/subdir/bibi-bookshelf/moby-dick` ではなく `s3://yourbucket/subdir/bibi-bookshelf/moby-dick-book`
* `s3://yourbucket/subdir/bibi/moby-dick.html` ではなく `s3://yourbucket/subdir/bibi/moby-dick-book.html`

=== HTMLを生成しない

    % bibi publish --bibi=s3://yourbucket/subdir/bibi --no-page path/to/moby-dick.epub moby-dick-book

コマンドに `--no-page` オプションを渡してください。

Bibiの通常のURIである `https://s3.your-region.amazonaws.com/yourbucket/subdir/bibi/?book=moby-dick-book` に行くことでEPUBを閲覧することはできます。

=== 生成するHTMLへの任意のフラグメントの挿入

bibi publish inserts HTML fragments from given files to at the end of `<head>` and `<body>` by `--head-end` and `--body-end` options respectively.

Assume we want to insert generator name in head element of Bibi HTML:

    % cat ./generator.html
    <meta name="generator" content="bibi publish">

Specify path to the the file by `--head-end` option:

    % bibi publish --bibi=s3://yourbucket/subdir/bibi --head-end=./generator.html path/to/moby-dick.epub

Now the HTML fragment is inserted into HTML file:

----
% curl -s https://s3.your-region.amazonaws.com/yourbucket/subdir/bibi/moby-dick.html | rg -B3 -A3 '</head>'
            <meta name="generator" content="bibi publish">


        </head>


        <body data-bibi-book="moby-dick">
----

`--body-end` option inserts HTML fragment in given file at just before `</body>` in HTML.

== 設定

You can configure bibi publish by the file `~/.config/bibi/publish.toml` in https://toml.io/[TOML] format. This is especially useful for avoiding to specify options such as `--bibi` and `--bookshelf` each time.

Example is here:

~/.config/bibi/publish.toml
[source,toml]
----
# `default` table is used by default
[default]
bibi = "s3://yourbucket/subdir/bibi"
bookshelf = "s3://yourbucket/epubs"
page = true
----

This is equivalent to pass command-line options `--bibi=s3://yourbucket/subdir/bibi`, `--bookshelf=s3://yourbucket/epubs` and `--page`.

If you want to switch set of configuration depending on situation, add another table and specify it by `--profile` option.

~/.config/bibi/publish.toml
[source,toml]
----
[production]
bibi = "s3://your-production-bucket/bibi"

[staging]
bibi = "s3://your-staging-bucket/bibi"

----

    % bibi publish --profile=staging moby-dick.epub

Currently supported keys are `bibi`, `bookshelf`, `page`, `head_end` and `body_end`.

=== AWSプロファイル

Use environment variable `AWS_PROFILE`:

    % AWS_PROFILE=publicbibi bibi publish path/to/doc.epub

== 参考

* https://github.com/satorumurmur/bibi[Bibi] is an EPUB reader which runs in web browser with beautiful UI.
* https://aws.amazon.com/cli/[AWS CLI] for install and configuration for AWS profile, which bibi publish also uses

== 著作権

Copyright (c) 2020 Kitaiti Makoto

See {file:COPYING.txt} for details.
